name: Test

on:
  push:
    branches: [main] # Run tests on every push to the main branch
  pull_request:
    branches: [main] # Run tests on every pull request targeting the main branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Navigate to project directory
        run: cd server

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
